name: Your New Jekyll Site

# Code highlighting
highlighter: pygments

navigation:
- text: About
  url: /
  active: /index.html
- text: Manifesto
  url: /manifesto
  active: /manifesto/index.html
- text: Blog
  url: http://blog.nooku.org

# We don't want to publish some files
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']