name: Nooku

description: Open Source PHP Framework for Web Applications. A project for developers integrators and hackers alike. Through collaboration we innovate and grow Nooku.
main_title: Noooku
url: http://www.nooku.org

navigation:
  - text: Features
    url: /features
    position: top
  - text: Get Started
    url: /get-started
    position: top
  - text: Services
    url: /services
    position: top
  - text: Docs
    url: /docs
    position: top
  - text: Blog
    url: /blog
    position: top
  - text: Events
    url: /events
    position: top
  - text: Platform
    url: /platform
    position: footer
  - text: Manifesto
    url: /manifesto
    position: footer
  - text: Facebook
    url: https://www.facebook.com/nooku.org
    position: footer
  - text: Twitter
    url: https://www.twitter.com/nooku
    position: footer
  - text: GitHub
    url: https://www.github.com/nooku
    position: footer
  - text: RSS
    url: /blog/rss.xml
    position: footer

monthly_archive:
  layout: archive
  path: blog

permalink: "/blog/:year/:month/:title"
paginate: 3
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-sitemap

# collections
collections:
- events

# We don't want to publish some files
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'README.md', 'node_modules', 'gruntfile.js', 'package.json', 'scripts', 'blog']