name: Your New Jekyll Site

navigation:
- text: About
  url: /
  active: /index.html
- text: Manifesto
  url: /manifesto
  active: /manifesto/index.html
- text: Blog
  url: /blog
  active: /blog/
  layout: blog
monthly_archive:
  path: blog

# Code highlighting
highlighter: pygments

# We don't want to publish some files
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']