name: Nooku

description: Nooku is a project for developers integrators and hackers alike. Through collaboration we innovate and grow Nooku
# url: http://localhost:4000

highlighter: pygments

navigation:
- text: About
- text: Manifesto
  url: manifesto
- text: Blog
  url: blog
  layout: blog

monthly_archive:
  layout: archive
  path: blog

paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-sitemap

# We don't want to publish some files
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'scripts']