name: Nooku

description: Open Source PHP Framework for Web Applications. A project for developers integrators and hackers alike. Through collaboration we innovate and grow Nooku.
main_title: Noooku
url: http://www.nooku.org

monthly_archive:
  layout: archive
  path: blog

permalink: "/blog/:year/:month/:title"
paginate: 3
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-sitemap

# collections
collections:
- events

# We don't want to publish some files
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'README.md', 'node_modules', 'gruntfile.js', 'package.json', 'scripts']