name: Your New Jekyll Site

navigation:
- text: About
- text: Manifesto
  url: manifesto
- text: Blog
  url: blog
  layout: blog

monthly_archive:
  layout: archive
  path: blog

# Code highlighting
highlighter: pygments

# We don't want to publish some files
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']