name: Nooku
description: Nooku is a project for developers integrators and hackers alike. Through collaboration we innovate and grow Nooku
url: http://nooku.org
pygments: true
navigation:
- text: About
- text: Manifesto
  url: manifesto
- text: Blog
  url: blog
  layout: blog

monthly_archive:
  layout: archive
  path: blog
paginate: 5
paginate_path: "blog/page:num"
